Add tags support
CloudHealth/terraform-cloudhealth-iam pull request #34
Opened 2021-06-08 08:12 UTC by sean-zou

2021-06-24 16:34 UTC, angelconcepcion requested changes

2021-06-24 16:34 UTC, angelconcepcion commented on README.md
> +    <td> A map of tags to assign to the taggble resources. (optional)</td>
Just fix the typo and we should be good with this.

2021-07-13 03:04 UTC, sean-zou commented on README.md
> +    <td> A map of tags to assign to the taggble resources. (optional)</td>
Fixed, thanks!

2021-07-13 14:20 UTC, angelconcepcion approved these changes

2021-07-13 14:20 UTC, merged